version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@nuxtjs/eslint-config"
    versions:
    - 6.0.0
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
